Repository dailry/dailry, pull requests merged in 2023-12, with the labels that each got.

#34 Feat/fe/#27
  frontend/.gitignore
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/package.json
  frontend/src/App.js
  frontend/src/constants/routes.js
  frontend/src/index.js
  frontend/src/pages/AdminMembersPage/AdminMembersPage.jsx
  frontend/src/pages/CommunityPage/CommunityPage.jsx
  frontend/src/pages/DailyPage/DailyPage.jsx
  frontend/src/pages/HomePage/HomePage.jsx
  frontend/src/pages/LoginPage/LoginPage.jsx
  frontend/src/pages/MyPage/MyPage.jsx
  frontend/src/pages/RegisterPage/RegisterPage.jsx
  frontend/src/stories/Button.jsx
  frontend/src/stories/Button.stories.js
  frontend/src/stories/Configure.mdx
  frontend/src/stories/Header.jsx
  frontend/src/stories/Header.stories.js
  frontend/src/stories/Page.jsx
  frontend/src/stories/Page.stories.js
  frontend/src/stories/assets/accessibility.png
  frontend/src/stories/assets/accessibility.svg
  frontend/src/stories/assets/addon-library.png
  frontend/src/stories/assets/assets.png
  frontend/src/stories/assets/avif-test-image.avif
  frontend/src/stories/assets/context.png
  frontend/src/stories/assets/discord.svg
  frontend/src/stories/assets/docs.png
  frontend/src/stories/assets/figma-plugin.png
  frontend/src/stories/assets/github.svg
  frontend/src/stories/assets/share.png
  frontend/src/stories/assets/styling.png
  frontend/src/stories/assets/testing.png
  frontend/src/stories/assets/theming.png
  frontend/src/stories/assets/tutorials.svg
  frontend/src/stories/assets/youtube.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
Labels: FE, 환경설정

#50 feat : 회원가입/로그인 작성
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/daily/daily/DaIlyApplication.java
  backend/src/main/java/com/daily/daily/TestController.java
  backend/src/main/java/com/daily/daily/auth/SecurityConfig.java
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/dto/LoginDto.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
  backend/src/main/java/com/daily/daily/auth/service/AuthService.java
  backend/src/main/java/com/daily/daily/auth/service/MemberDetailsService.java
  backend/src/main/java/com/daily/daily/common/domain/BaseTimeEntity.java
  backend/src/main/java/com/daily/daily/common/dto/CommonResponseDTO.java
  backend/src/main/java/com/daily/daily/member/constant/MemberRole.java
  backend/src/main/java/com/daily/daily/member/controller/MemberController.java
  backend/src/main/java/com/daily/daily/member/domain/Member.java
  backend/src/main/java/com/daily/daily/member/dto/JoinDTO.java
  backend/src/main/java/com/daily/daily/member/repository/MemberRepository.java
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
Labels: BE, 🌱 신규 기능

#54 임시 테스트코드 삭제
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
Labels: BE, ✨ 리팩터링

#59 소셜 로그인 구현
  backend/build.gradle
  backend/src/main/java/com/daily/daily/auth/config/SecurityConfig.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
  backend/src/main/java/com/daily/daily/member/constant/MemberRole.java
  backend/src/main/java/com/daily/daily/member/domain/Member.java
  backend/src/main/java/com/daily/daily/member/repository/MemberRepository.java
  backend/src/main/java/com/daily/daily/oauth/OAuth2CustomUser.java
  backend/src/main/java/com/daily/daily/oauth/OAuthAttributes.java
  backend/src/main/java/com/daily/daily/oauth/constant/SocialType.java
  backend/src/main/java/com/daily/daily/oauth/controller/OauthController.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2FailureHandler.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
  backend/src/main/java/com/daily/daily/oauth/provider/GoogleUserInfo.java
  backend/src/main/java/com/daily/daily/oauth/provider/KakaoUserInfo.java
  backend/src/main/java/com/daily/daily/oauth/provider/OAuth2UserInfo.java
  backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
Labels: BE, 🌱 신규 기능

#63 로그인 페이지 디자인
  frontend/.storybook/GlobalStyles.js
  frontend/.storybook/preview.jsx
  frontend/build-storybook.log
  frontend/package.json
  frontend/src/assets/png/google-logo.png
  frontend/src/assets/png/index.js
  frontend/src/assets/png/kakao-logo.png
  frontend/src/components/common/AuthButton/AuthButton.jsx
  frontend/src/components/common/AuthButton/AuthButton.stories.js
  frontend/src/components/common/AuthButton/AuthButton.styled.jsx
  frontend/src/components/common/Input/Input.jsx
  frontend/src/components/common/Input/Input.stories.js
  frontend/src/components/common/Input/Input.styled.jsx
  frontend/src/components/common/Text/Text.jsx
  frontend/src/components/common/Text/Text.stories.js
  frontend/src/components/common/Text/Text.styled.jsx
  frontend/src/index.js
  frontend/src/pages/LoginPage/LoginPage.jsx
  frontend/src/pages/LoginPage/LoginPage.styled.jsx
  frontend/src/pages/Template/OnesideTemplate.jsx
  frontend/src/pages/Template/OnesideTemplate.styled.jsx
  frontend/src/stories/Button.jsx
  frontend/src/stories/Button.stories.js
  frontend/src/stories/Configure.mdx
  frontend/src/stories/Header.jsx
  frontend/src/stories/Header.stories.js
  frontend/src/stories/Page.jsx
  frontend/src/stories/Page.stories.js
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
  frontend/src/styles/GlobalStyle.js
  frontend/src/styles/color.js
Labels: FE

#66 깃허브 액션에서 submoudle을 사용하도록 수정
  .github/workflows/backend-dev-cicd.yml
Labels: BE, ✨ 리팩터링, 환경설정

#71 Auth, OAuth 패키지 테스트 코드 작성
  backend/build.gradle
  backend/src/main/java/com/daily/daily/oauth/controller/OauthController.java
  backend/src/main/java/com/daily/daily/oauth/provider/KakaoUserInfo.java
  backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
  backend/src/test/java/com/daily/daily/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/daily/daily/auth/jwt/JwtUtilTest.java
  backend/src/test/java/com/daily/daily/auth/service/AuthServiceTest.java
  backend/src/test/java/com/daily/daily/oauth/controller/OauthControllerTest.java
Labels: BE, ✨ 리팩터링

#76 저번 주 작업 리팩토링
  backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
  backend/src/main/java/com/daily/daily/auth/config/SecurityConfig.java
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/dto/JwtClaimDTO.java
  backend/src/main/java/com/daily/daily/auth/dto/LoginDTO.java
  backend/src/main/java/com/daily/daily/auth/exception/LoginFailureException.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
  backend/src/main/java/com/daily/daily/auth/service/AuthService.java
  backend/src/main/java/com/daily/daily/common/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/daily/daily/member/controller/MemberController.java
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
  backend/src/test/java/com/daily/daily/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/daily/daily/auth/jwt/JwtUtilTest.java
  backend/src/test/java/com/daily/daily/auth/service/AuthServiceTest.java
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
  backend/src/test/java/com/daily/daily/member/service/MemberServiceTest.java
  backend/src/test/java/com/daily/daily/oauth/controller/OauthControllerTest.java
Labels: BE, ✨ 리팩터링, 테스트

#80 oAuth, member 코드 리팩토링
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/main/java/com/daily/daily/member/validator/NicknameValidator.java
  backend/src/main/java/com/daily/daily/oauth/OAuth2CustomUser.java
  backend/src/main/java/com/daily/daily/oauth/OAuthAttributes.java
  backend/src/main/java/com/daily/daily/oauth/constant/SocialType.java
  backend/src/main/java/com/daily/daily/oauth/controller/OauthController.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2FailureHandler.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
  backend/src/main/java/com/daily/daily/oauth/provider/GoogleUserInfo.java
  backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
Labels: BE, ✨ 리팩터링

#85 회원가입시 닉네임 부여 기능 구현
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/main/java/com/daily/daily/member/service/NicknameGenerator.java
  backend/src/main/java/com/daily/daily/oauth/OAuthAttributes.java
  backend/src/main/java/com/daily/daily/oauth/provider/KakaoUserInfo.java
  backend/src/main/java/com/daily/daily/oauth/service/CustomOAuth2UserService.java
  backend/src/test/java/com/daily/daily/member/service/MemberServiceTest.java
Labels: BE, 🌱 신규 기능

#79 각 페이지에 적용될 레이아웃 및 레이아웃 의 프레임 추가
  frontend/src/App.js
  frontend/src/components/common/Layout/DefaultLayout.jsx
  frontend/src/components/common/Layout/RootLayout/RootLayout.jsx
  frontend/src/components/common/Layout/RootLayout/RootLayout.styled.jsx
  frontend/src/components/common/Navigation/DefaultNavigation.jsx
  frontend/src/components/common/PageTemplate/PageTemplate.styled.jsx
  frontend/src/pages/LoginPage/LoginPage.jsx
  frontend/src/pages/Template/OnesideTemplate.jsx
Labels: FE, 🌱 신규 기능

#88 Storybook workflow의 No package.json 해결
  .github/CODEOWNERS
  .github/workflows/chromatic.yml
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.storybook/main.js
  frontend/build-storybook.log
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/pages/HomePage/HomePage.jsx
  frontend/src/stories/Configure.mdx
Labels: FE, 환경설정
