Repository dailry/dailry, pull requests merged in 2024-03, with the labels that each got.

#258 좋아요 기능 리팩토링 (반정규화, 동시성 문제 해소)
  backend/src/main/java/com/daily/daily/member/domain/Member.java
  backend/src/main/java/com/daily/daily/post/PostExceptionHandler.java
  backend/src/main/java/com/daily/daily/post/controller/PostLikeController.java
  backend/src/main/java/com/daily/daily/post/domain/Post.java
  backend/src/main/java/com/daily/daily/post/dto/PostReadResponseDTO.java
  backend/src/main/java/com/daily/daily/post/exception/NotPreviouslyLikedException.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepository.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydsl.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydslImpl.java
  backend/src/main/java/com/daily/daily/post/service/PostLikeFacade.java
  backend/src/main/java/com/daily/daily/post/service/PostLikeService.java
  backend/src/main/java/com/daily/daily/post/service/PostService.java
  backend/src/main/resources/db/migration/V202402281407__addLikeCount.sql
  backend/src/main/resources/db/migration/V202403011442__addVersionToPost.sql
  backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
  backend/src/test/java/com/daily/daily/post/service/PostLikeServiceConcurrencyTest.java
  backend/src/test/java/com/daily/daily/post/service/PostLikeServiceTest.java
  backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
  backend/src/test/java/com/daily/daily/testutil/config/JpaTest.java
  backend/src/test/java/com/daily/daily/testutil/generator/DailryPageGenerator.java
  backend/src/test/java/com/daily/daily/testutil/generator/MemberGenerator.java
  backend/src/test/java/com/daily/daily/testutil/generator/PostGenerator.java
  backend/src/test/resources/application.yml
Labels: BE, ✨ 리팩터링

#265 다일리 페이지 수정 API 연동
  frontend/src/apis/dailryApi.js
  frontend/src/constants/toolbar.js
  frontend/src/hooks/useNewDecorateComponent/properties.js
  frontend/src/hooks/usePageData.jsx
  frontend/src/pages/DailryPage/DailryPage.jsx
  frontend/src/pages/DailryPage/DailryPage.styled.jsx
Labels: FE, 🌱 신규 기능

#266 선택된 다일리 및 페이지가 없을 때 처리
  frontend/src/components/common/Hamburger/DailryHamburger.jsx
  frontend/src/components/common/Navigation/DailryNavigation.jsx
  frontend/src/components/da-ily/PageListModal/PageListModal.jsx
  frontend/src/hooks/useDailryContext.jsx
  frontend/src/pages/DailryPage/DailryPage.jsx
  frontend/src/pages/DailryPage/DailryPage.styled.jsx
Labels: FE, 🌱 신규 기능

#269 해시태그 검색 기능 구현
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/post/controller/PostController.java
  backend/src/main/java/com/daily/daily/post/dto/PostReadByHashTagRequestDTO.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydsl.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydslImpl.java
  backend/src/main/java/com/daily/daily/post/service/PostService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
  backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
Labels: BE, 🌱 신규 기능

#272 인기 다일리 페이지 게시글 기능 추가
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
  backend/src/main/java/com/daily/daily/common/config/Business/BusinessConfig.java
  backend/src/main/java/com/daily/daily/post/controller/HotPostController.java
  backend/src/main/java/com/daily/daily/post/domain/HotPost.java
  backend/src/main/java/com/daily/daily/post/domain/Post.java
  backend/src/main/java/com/daily/daily/post/dto/HotPostReadResponseDTO.java
  backend/src/main/java/com/daily/daily/post/dto/HotPostReadSliceResponseDTO.java
  backend/src/main/java/com/daily/daily/post/dto/PostReadSliceResponseDTO.java
  backend/src/main/java/com/daily/daily/post/repository/HotPostRepository.java
  backend/src/main/java/com/daily/daily/post/repository/HotPostRepositoryQuerydsl.java
  backend/src/main/java/com/daily/daily/post/repository/HotPostRepositoryQuerydslImpl.java
  backend/src/main/java/com/daily/daily/post/repository/PostLikeRepository.java
  backend/src/main/java/com/daily/daily/post/service/HotPostService.java
  backend/src/main/java/com/daily/daily/post/service/PostLikeFacade.java
  backend/src/main/java/com/daily/daily/post/service/PostLikeService.java
  backend/src/main/resources/db/migration/V202403041352__addHotPostTable.sql
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/post/controller/HotPostControllerTest.java
  backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
  backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
  backend/src/test/java/com/daily/daily/post/fixture/HotPostFixture.java
  backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
  backend/src/test/java/com/daily/daily/post/service/PostLikeServiceConcurrencyTest.java
  backend/src/test/java/com/daily/daily/post/service/PostLikeServiceTest.java
Labels: BE, 🌱 신규 기능

#273 버그수정 이슈 템플릿 추가 / fix 브랜치 자동생성 기능 추가
  .github/ISSUE_TEMPLATE/fix.yml
  .github/issue-branch.yml
  .github/workflows/create-issue-branch.yml
Labels: 🌱 신규 기능, ✨ 리팩터링, 문서, 환경설정

#275 다일리 페이지 삭제 버그 수정
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydsl.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImpl.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/test/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImplTest.java
  backend/src/test/java/com/daily/daily/testutil/generator/DailryPageGenerator.java
Labels: BE, 🔧 버그 수정

#277 다일리 페이지 수정 API 꾸미기 컴포넌트 삭제 기능 반영하기 / S3 Storage 리팩토링
  backend/src/main/java/com/daily/daily/common/domain/DirectoryPath.java
  backend/src/main/java/com/daily/daily/common/exception/InvalidDirectoryException.java
  backend/src/main/java/com/daily/daily/common/service/S3StorageService.java
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/java/com/daily/daily/post/service/PostService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/common/file_save/DirectoryPathTest.java
  backend/src/test/java/com/daily/daily/common/service/S3StorageServiceTest.java
  backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
  backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
  backend/src/test/java/com/daily/daily/dailrypage/service/DailryPageServiceTest.java
  backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
Labels: BE, ✨ 리팩터링

#282 마이페이지 구현
  frontend/src/apis/memberApi.js
  frontend/src/components/common/Button/Button.styled.jsx
  frontend/src/pages/MyPage/MyPage.jsx
  frontend/src/pages/MyPage/MyPage.styled.js
Labels: FE, 🌱 신규 기능

#288 다일리페이지 생성할 때 초기 Thumbnail 연결하기
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageCreateResponseDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
  backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
Labels: BE, ✨ 리팩터링

#290 회원 탈퇴 기능 수정
  backend/src/main/java/com/daily/daily/member/domain/Member.java
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
Labels: BE, ✨ 리팩터링

#293 액세스 토큰 만료시 리프레쉬 재발급 로직 추가
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
  backend/src/main/java/com/daily/daily/auth/service/TokenService.java
  backend/src/main/resources/static/docs/api-document.html
Labels: BE, ✨ 리팩터링

#303 customAxios header에서 Authorization 삭제
  frontend/src/apis/customAxios.js
Labels: FE, 🚨 긴급
