Repository dailry/dailry, pull requests merged in 2024-02, with the labels that each got.

#209 테스트 코드에서 @MockBean(JpaMetamodelMappingContext.class) 제거
  backend/src/main/java/com/daily/daily/DaIlyApplication.java
  backend/src/main/java/com/daily/daily/common/config/JPAConfig.java
  backend/src/test/java/com/daily/daily/dailry/controller/DailryControllerTest.java
  backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
  backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
  backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
  backend/src/test/java/com/daily/daily/postcomment/controller/PostCommentControllerTest.java
  backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcTest.java
Labels: BE, ✨ 리팩터링, 테스트, 환경설정

#211 다일리 네비게이션 제작
  frontend/.gitignore
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/App.js
  frontend/src/apis/dailryApi.js
  frontend/src/components/common/Hamburger/DailryHamburger.jsx
  frontend/src/components/common/Hamburger/Hamburger.jsx
  frontend/src/components/common/Hamburger/Hamburger.styled.jsx
  frontend/src/components/common/Layout/DefaultLayout.jsx
  frontend/src/components/common/Layout/RootLayout/RootLayout.jsx
  frontend/src/components/common/Layout/RootLayout/RootLayout.styled.jsx
  frontend/src/components/common/Navigation/AdminNavigation.jsx
  frontend/src/components/common/Navigation/CommunityNavigation.jsx
  frontend/src/components/common/Navigation/DailryNavigation.jsx
  frontend/src/components/common/Navigation/DefaultNavigation.jsx
  frontend/src/components/common/Navigation/NameArea.jsx
  frontend/src/components/common/Navigation/Navigation.jsx
  frontend/src/components/common/Navigation/Navigation.styled.jsx
  frontend/src/components/common/NavigationItem/NavigationInput.jsx
  frontend/src/components/common/NavigationItem/NavigationItem.jsx
  frontend/src/components/common/NavigationItem/NavigationItem.styled.jsx
  frontend/src/components/common/PageTemplate/PageTemplate.styled.jsx
  frontend/src/hooks/useDailryContext.jsx
  frontend/src/index.js
  frontend/src/mocks/datas/dailry.js
  frontend/src/mocks/datas/member.js
  frontend/src/mocks/handlers/auth.js
  frontend/src/mocks/handlers/comments.js
  frontend/src/mocks/handlers/dailry.js
  frontend/src/mocks/handlers/member.js
  frontend/src/mocks/handlers/posts.js
  frontend/src/mocks/worker.js
  frontend/src/styles/color.js
Labels: FE, 🌱 신규 기능

#215 엔티티 클래스에서 @AllArgsConstructor 제거하기
  backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/member/domain/Member.java
  backend/src/main/java/com/daily/daily/post/domain/Hashtag.java
  backend/src/main/java/com/daily/daily/post/domain/Post.java
  backend/src/main/java/com/daily/daily/post/domain/PostHashtag.java
  backend/src/main/java/com/daily/daily/post/domain/PostLike.java
  backend/src/main/java/com/daily/daily/postcomment/domain/PostComment.java
  backend/src/main/java/com/daily/daily/postcomment/service/PostCommentService.java
  backend/src/test/java/com/daily/daily/dailry/fixture/DailryFixture.java
  backend/src/test/java/com/daily/daily/member/fixture/MemberFixture.java
  backend/src/test/java/com/daily/daily/member/service/MemberEmailServiceTest.java
  backend/src/test/java/com/daily/daily/member/service/MemberServiceTest.java
  backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
  backend/src/test/java/com/daily/daily/postcomment/fixture/PostCommentFixture.java
  backend/src/test/java/com/daily/daily/postcomment/service/PostCommentServiceTest.java
Labels: BE, ✨ 리팩터링, 테스트

#217 다일리 페이지 관련 리팩토링
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageCreateResponseDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageThumbnailDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydsl.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImpl.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/java/com/daily/daily/post/controller/PostController.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
  backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
Labels: BE, ✨ 리팩터링, 문서

#214 다일리 페이지 추가 기능
  frontend/src/apis/dailryApi.js
  frontend/src/assets/svg/add-page-icon.svg
  frontend/src/assets/svg/index.js
  frontend/src/assets/svg/left-arrow-icon.svg
  frontend/src/assets/svg/right-arrow-icon.svg
  frontend/src/constants/toolbar.js
  frontend/src/mocks/datas/dailry.js
  frontend/src/mocks/handlers/dailry.js
  frontend/src/pages/DailryPage/DailryPage.jsx
  frontend/src/pages/DailryPage/DailryPage.styled.jsx
Labels: FE, 🌱 신규 기능

#228 네비게이션 버그 수정
  frontend/src/components/common/Hamburger/DailryHamburger.jsx
Labels: FE, 🐞 버그

#231 react-toastify 사용
  frontend/package.json
  frontend/src/index.js
  frontend/src/pages/DailryPage/DailryPage.jsx
Labels: FE, 🌱 신규 기능

#237 Feat/fe/#236
  frontend/.gitignore
  frontend/package.json
  frontend/src/apis/memberApi.js
Labels: FE, 환경설정

#244 API 문서 리팩토링하기
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
  backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcConstant.java
  backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcTest.java
  backend/src/test/java/com/daily/daily/testutil/mockmvc/MockMvcUtil.java
Labels: BE, 문서

#246 CorsConfig 에서 Profile 별로 설정 빈을 다르게 등록하기
  backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
Labels: BE, ✨ 리팩터링

#252 DailryNotFoundException 익셉션 핸들러로 처리하기
  backend/src/main/java/com/daily/daily/dailry/DailryExceptionHandler.java
Labels: BE, ✨ 리팩터링

#253 로그인 관련 api와 링크 연결
  frontend/src/apis/customAxios.js
  frontend/src/apis/loginApi.js
  frontend/src/apis/memberApi.js
  frontend/src/apis/postApi.js
  frontend/src/index.js
  frontend/src/pages/JoinPage/JoinDone.jsx
  frontend/src/pages/LoginPage/FindIdForm.jsx
  frontend/src/pages/LoginPage/FindIdPage.jsx
  frontend/src/pages/LoginPage/LoginPage.jsx
  frontend/src/pages/LoginPage/LoginPage.styled.jsx
  frontend/src/pages/LoginPage/SentId.jsx
  frontend/src/pages/LoginPage/SentPassword.jsx
  frontend/src/pages/MyPage/MyPage.jsx
  frontend/src/pages/MyPage/MyPage.styled.js
Labels: FE, 🌱 신규 기능

#256 다일리 페이지 미리보기 버그 수정하기
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImpl.java
  backend/src/test/java/com/daily/daily/dailrypage/repository/DailryPageQuerydslImplTest.java
  backend/src/test/java/com/daily/daily/member/repository/MemberRepositoryTest.java
  backend/src/test/java/com/daily/daily/post/repository/PostLikeRepositoryTest.java
  backend/src/test/java/com/daily/daily/postcomment/repository/PostCommentRepositoryTest.java
  backend/src/test/java/com/daily/daily/testutil/config/JpaTest.java
  backend/src/test/java/com/daily/daily/testutil/generator/DailryGenerator.java
  backend/src/test/java/com/daily/daily/testutil/generator/DailryPageGenerator.java
Labels: BE, ✨ 리팩터링, 🐞 버그
