Repository dailry/dailry, pull requests merged in 2024-01, with the labels that each got.

#99 refresh 토큰 관련 기능 구현
  backend/build.gradle
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/controller/TokenController.java
  backend/src/main/java/com/daily/daily/auth/dto/TokenDTO.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
  backend/src/main/java/com/daily/daily/auth/jwt/RefreshToken.java
  backend/src/main/java/com/daily/daily/auth/jwt/RefreshTokenRepository.java
  backend/src/main/java/com/daily/daily/auth/service/AuthService.java
  backend/src/main/java/com/daily/daily/auth/service/TokenService.java
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
  backend/src/test/java/com/daily/daily/auth/jwt/JwtUtilTest.java
  backend/src/test/java/com/daily/daily/member/service/MemberServiceTest.java
Labels: BE, 🌱 신규 기능

#100 refresh 토큰 리뷰 반영 수정
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/controller/TokenController.java
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
Labels: BE, ✨ 리팩터링

#101 로그인, 회원가입 페이지 디자인
  frontend/src/App.js
  frontend/src/components/common/Layout/RootLayout/RootLayout.jsx
  frontend/src/constants/routes.js
  frontend/src/pages/LoginPage/FindIdPage.jsx
  frontend/src/pages/LoginPage/SentId.jsx
  frontend/src/pages/LoginPage/SentPassword.jsx
  frontend/src/pages/RegisterPage/RegisterDone.jsx
  frontend/src/pages/RegisterPage/RegisterPage.jsx
  frontend/src/pages/RegisterPage/RegisterPage.styled.jsx
Labels: FE, 🌱 신규 기능

#115 인증 & 인가 API restdocs 작성
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/service/TokenService.java
  backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
Labels: BE, 문서

#111 홈 화면 디자인 완성
  frontend/src/App.js
  frontend/src/assets/svg/index.js
  frontend/src/assets/svg/ring-icon.svg
  frontend/src/pages/HomePage/HomePage.jsx
  frontend/src/pages/HomePage/HomePage.styled.jsx
  frontend/src/styles/color.js
Labels: FE

#119 defaultSuccessfulURL 제거
  backend/src/main/java/com/daily/daily/auth/config/SecurityConfig.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
Labels: BE, 🐞 버그

#123 로그아웃 기능 구현
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/dto/TokenDTO.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/daily/daily/auth/service/AuthService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
Labels: BE, 🌱 신규 기능

#122 feat:회원 가입, 회원 정보 조회 api 연동 및 form 관련 커스텀 훅 추가
  frontend/src/App.js
  frontend/src/apis/memberApi.js
  frontend/src/components/common/AuthButton/AuthButton.jsx
  frontend/src/constants/routes.js
  frontend/src/hooks/useForm.jsx
  frontend/src/pages/JoinPage/JoinDone.jsx
  frontend/src/pages/JoinPage/JoinForm.jsx
  frontend/src/pages/JoinPage/JoinPage.jsx
  frontend/src/pages/JoinPage/JoinPage.styled.jsx
  frontend/src/pages/RegisterPage/RegisterPage.jsx
Labels: FE, 🌱 신규 기능

#134 코드 수정 및 Restdocs 수정 작업
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
  backend/src/main/java/com/daily/daily/member/controller/MemberController.java
  backend/src/main/java/com/daily/daily/oauth/handler/OAuth2SuccessHandler.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/daily/daily/integration/auth/jwt/JwtUtilTest.java
  backend/src/test/java/com/daily/daily/integration/oauth/controller/OauthControllerTest.java
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
Labels: BE, ✨ 리팩터링

#139 배포스크립트 수정 / ✨ 리팩터링 라벨 붙어도, 이슈 브랜치 생성
  .github/workflows/create-issue-branch.yml
  backend/scripts/deploy.sh
Labels: BE, ✨ 리팩터링, 환경설정

#140 JwtAuthorizationFilter 코드 수정
  backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
Labels: BE, ✨ 리팩터링

#143 토큰 관련 수정 작업
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/exception/TokenExpiredException.java
  backend/src/main/java/com/daily/daily/auth/jwt/JwtUtil.java
  backend/src/main/java/com/daily/daily/auth/service/AuthService.java
  backend/src/main/java/com/daily/daily/auth/service/TokenService.java
Labels: BE, ✨ 리팩터링

#147 버그수정 및 리팩토링
  backend/scripts/deploy.sh
  backend/src/main/java/com/daily/daily/auth/config/CorsConfig.java
  backend/src/main/java/com/daily/daily/auth/config/SecurityConfig.java
  backend/src/main/java/com/daily/daily/auth/controller/AuthController.java
  backend/src/main/java/com/daily/daily/auth/service/MemberDetailsService.java
  backend/src/main/java/com/daily/daily/common/dto/CommonResponseDTO.java
  backend/src/main/java/com/daily/daily/common/dto/SuccessResponseDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/java/com/daily/daily/member/controller/MemberController.java
  backend/src/main/java/com/daily/daily/member/domain/Member.java
  backend/src/main/java/com/daily/daily/member/dto/JoinDTO.java
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/test/java/com/daily/daily/TestControllerTest.java
  backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
Labels: BE, ✨ 리팩터링, 🐞 버그

#144 그림 그리기 꾸미기 컴포넌트
  frontend/src/components/decorate/Drawing/Draw.js
  frontend/src/components/decorate/Drawing/Drawing.jsx
  frontend/src/components/decorate/Drawing/canvas.js
  frontend/src/components/decorate/Drawing/useDrawInstance.jsx
  frontend/src/components/decorate/Drawing/useDrawUtils.jsx
  frontend/src/hooks/useDomContentsLoaded.jsx
  frontend/src/pages/DailyPage/DailyPage.jsx
  frontend/src/utils/dataFormatting.js
Labels: FE, 🌱 신규 기능

#149 리사이징, 드래그 기능
  frontend/package.json
  frontend/src/App.js
  frontend/src/assets/svg/add-page-icon.svg
  frontend/src/assets/svg/cursor-icon.svg
  frontend/src/assets/svg/draw-icon.svg
  frontend/src/assets/svg/text-icon.svg
  frontend/src/components/common/Layout/RootLayout/RootLayout.jsx
  frontend/src/components/common/Layout/RootLayout/RootLayout.styled.jsx
  frontend/src/components/common/NavigationItem/NavigationItem.styled.jsx
  frontend/src/components/da-ily/Wrapper/Element.jsx
  frontend/src/pages/DailyPage/DailyPage.jsx
  frontend/src/pages/DailyPage/DailyPage.styled.jsx
  frontend/src/pages/DailyPage/dailry.json
  frontend/src/styles/color.js
Labels: FE, 🌱 신규 기능

#155 커뮤니티 글 생성 기능 구현
  .github/workflows/backend-dev-cicd.yml
  backend/build.gradle
  backend/src/main/java/com/daily/daily/common/GlobalExceptionHandler.java
  backend/src/main/java/com/daily/daily/common/config/S3Config.java
  backend/src/main/java/com/daily/daily/common/domain/BaseTimeEntity.java
  backend/src/main/java/com/daily/daily/common/exception/FileContentTypeUnmatchedException.java
  backend/src/main/java/com/daily/daily/common/exception/FileUploadFailureException.java
  backend/src/main/java/com/daily/daily/common/service/S3StorageService.java
  backend/src/main/java/com/daily/daily/post/controller/PostController.java
  backend/src/main/java/com/daily/daily/post/domain/Post.java
  backend/src/main/java/com/daily/daily/post/dto/PostCreateDTO.java
  backend/src/main/java/com/daily/daily/post/dto/PostResponseDTO.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepository.java
  backend/src/main/java/com/daily/daily/post/service/PostService.java
  backend/src/test/java/com/daily/daily/common/service/S3StorageServiceTest.java
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
  backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
  backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
Labels: BE, 🌱 신규 기능

#157 컴포넌트 회전 기능 구현
  frontend/package.json
  frontend/src/components/da-ily/Moveable/Moveable.jsx
  frontend/src/components/da-ily/Wrapper/Element.jsx
  frontend/src/pages/DailyPage/DailyPage.jsx
  frontend/src/pages/DailyPage/DailyPage.styled.jsx
  frontend/src/pages/DailyPage/tmpDailryData.json
Labels: FE, 🌱 신규 기능

#162 다일리, 다일리 페이지 관련 기능 구현하기
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/dailry/controller/DailryController.java
  backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
  backend/src/main/java/com/daily/daily/dailry/dto/DailryDTO.java
  backend/src/main/java/com/daily/daily/dailry/dto/DailryUpdateDTO.java
  backend/src/main/java/com/daily/daily/dailry/exception/DialryNotFoundException.java
  backend/src/main/java/com/daily/daily/dailry/repository/DailryRepository.java
  backend/src/main/java/com/daily/daily/dailry/service/DailryService.java
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/java/com/daily/daily/member/domain/Member.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/dailry/controller/DailryControllerTest.java
  backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
Labels: BE, 🌱 신규 기능

#170 회원 탈퇴 기능 구현
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/auth/dto/LoginDTO.java
  backend/src/main/java/com/daily/daily/auth/dto/TokenDTO.java
  backend/src/main/java/com/daily/daily/member/controller/MemberController.java
  backend/src/main/java/com/daily/daily/member/service/MemberService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/integration/auth/controller/AuthControllerTest.java
  backend/src/test/java/com/daily/daily/integration/dailry/controller/DailryControllerTest.java
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
Labels: BE, 🌱 신규 기능

#174 다일리 페이지 수정로직 변경
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
Labels: BE, ✨ 리팩터링

#181 토큰 검증에서 문제가 발생할 경우 에러 응답이 작성되지 않는 문제 해결
  backend/src/main/java/com/daily/daily/auth/jwt/JwtAuthorizationFilter.java
Labels: BE, 🐞 버그

#187 페이지 수정 API 요청 포맷 변경 및 Validation 추가
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
Labels: BE, ✨ 리팩터링

#192 다일리, 다일리페이지 전체 리스트 조회
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/dailry/controller/DailryController.java
  backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
  backend/src/main/java/com/daily/daily/dailry/dto/DailryFindDTO.java
  backend/src/main/java/com/daily/daily/dailry/exception/DailryNotFoundException.java
  backend/src/main/java/com/daily/daily/dailry/repository/DailryRepository.java
  backend/src/main/java/com/daily/daily/dailry/service/DailryService.java
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageFindDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/dailry/controller/DailryControllerTest.java
Labels: BE, 🌱 신규 기능

#190 텍스트 박스 꾸미기 컴포넌트 추가
  frontend/src/components/decorate/TextBox/TextBox.jsx
  frontend/src/components/decorate/TextBox/TextBox.styled.jsx
Labels: FE, 🌱 신규 기능

#193 게시글에 해시태그 기능 추가
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/post/controller/PostController.java
  backend/src/main/java/com/daily/daily/post/domain/Hashtag.java
  backend/src/main/java/com/daily/daily/post/domain/Post.java
  backend/src/main/java/com/daily/daily/post/domain/PostHashtag.java
  backend/src/main/java/com/daily/daily/post/dto/PostReadResponseDTO.java
  backend/src/main/java/com/daily/daily/post/dto/PostWriteRequestDTO.java
  backend/src/main/java/com/daily/daily/post/dto/PostWriteResponseDTO.java
  backend/src/main/java/com/daily/daily/post/repository/HashtagRepository.java
  backend/src/main/java/com/daily/daily/post/repository/PostHashtagRepository.java
  backend/src/main/java/com/daily/daily/post/service/HashtagService.java
  backend/src/main/java/com/daily/daily/post/service/PostService.java
  backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
  backend/src/test/java/com/daily/daily/post/service/HashtagServiceTest.java
  backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
Labels: BE, 🌱 신규 기능

#196 api 문서 수정
  backend/src/main/java/com/daily/daily/dailry/controller/DailryController.java
  backend/src/main/java/com/daily/daily/dailry/dto/DailryDTO.java
  backend/src/main/java/com/daily/daily/dailry/dto/DailryFindDTO.java
  backend/src/main/java/com/daily/daily/dailry/dto/DailryUpdateDTO.java
  backend/src/main/java/com/daily/daily/dailry/repository/DailryRepository.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageFindDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/java/com/daily/daily/member/dto/MemberInfoDTO.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/dailry/controller/DailryControllerTest.java
  backend/src/test/java/com/daily/daily/dailry/fixture/DailryFixture.java
  backend/src/test/java/com/daily/daily/member/controller/MemberControllerTest.java
Labels: BE, ✨ 리팩터링

#197 게시글 조회 (무한스크롤) 기능 구현 및 Restdocs
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/post/controller/PostController.java
  backend/src/main/java/com/daily/daily/post/domain/Post.java
  backend/src/main/java/com/daily/daily/post/dto/PostReadResponseDTO.java
  backend/src/main/java/com/daily/daily/post/dto/PostReadSliceResponseDTO.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepository.java
  backend/src/main/java/com/daily/daily/post/service/PostService.java
  backend/src/main/java/com/daily/daily/postcomment/dto/PostCommentSliceDTO.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/post/controller/PostControllerTest.java
  backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
  backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
Labels: BE, 🌱 신규 기능

#199 다일리, 다일리 페이지 소유권 검사 로직 구현
  backend/src/main/java/com/daily/daily/dailry/domain/Dailry.java
  backend/src/main/java/com/daily/daily/dailry/service/DailryService.java
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/resources/static/docs/api-document.html
Labels: BE, 🌱 신규 기능

#201 DailryPageController 테스트 코드 작성 및 restdocs 작성
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageCreateResponseDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPagePreviewDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageThumbnailDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/dto/DailryPageUpdateDTO.java
  backend/src/main/java/com/daily/daily/dailrypage/repository/DailryPageRepository.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
  backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
Labels: BE, ✨ 리팩터링, 테스트, 문서

#203 섬네일 저장 기능 구현
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/dailrypage/controller/DailryPageController.java
  backend/src/main/java/com/daily/daily/dailrypage/domain/DailryPage.java
  backend/src/main/java/com/daily/daily/dailrypage/exception/DailryPageThumbnailNotFoundException.java
  backend/src/main/java/com/daily/daily/dailrypage/service/DailryPageService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/dailrypage/controller/DailryPageControllerTest.java
  backend/src/test/java/com/daily/daily/dailrypage/fixture/DailryPageFixture.java
Labels: BE, 🌱 신규 기능
