Repository dailry/dailry, pull requests merged in 2024-06, with the labels that each got.

#328 유저가 좋아요 눌렀는지 여부를 확인하는 API 개발
  backend/src/docs/asciidoc/api-document.adoc
  backend/src/main/java/com/daily/daily/post/controller/PostLikeController.java
  backend/src/main/java/com/daily/daily/post/domain/PostLike.java
  backend/src/main/java/com/daily/daily/post/repository/PostLikeRepository.java
  backend/src/main/java/com/daily/daily/post/service/PostLikeService.java
  backend/src/main/resources/static/docs/api-document.html
  backend/src/test/java/com/daily/daily/post/controller/PostLikeControllerTest.java
  backend/src/test/java/com/daily/daily/post/fixture/PostLikeFixture.java
  backend/src/test/java/com/daily/daily/post/service/PostLikeServiceTest.java
Labels: BE, 🌱 신규 기능

#322 다일리 ver.0 개선사항 대부분
  frontend/src/apis/memberApi.js
  frontend/src/apis/postApi.js
  frontend/src/assets/svg/back-icon.svg
  frontend/src/assets/svg/dailry-logo-icon.svg
  frontend/src/assets/svg/index.js
  frontend/src/components/common/Layout/RootLayout/RootLayout.jsx
  frontend/src/components/common/Layout/RootLayout/RootLayout.styled.jsx
  frontend/src/components/common/Navigation/CommunityNavigation.jsx
  frontend/src/components/common/Navigation/NameArea.jsx
  frontend/src/components/common/Navigation/Navigation.styled.jsx
  frontend/src/components/common/NavigationItem/NavigationItem.styled.jsx
  frontend/src/components/da-ily/ToolButton/ToolButton.stories.js
  frontend/src/pages/CommunityPage/CommunityPage.jsx
  frontend/src/pages/CommunityPage/CommunityPage.styled.jsx
  frontend/src/pages/CommunityPage/CommunityWritePage.jsx
  frontend/src/pages/DailryPage/DailryPage.jsx
  frontend/src/pages/HomePage/HomePage.jsx
  frontend/src/pages/MyPage/MyPage.jsx
  frontend/src/styles/color.js
Labels: FE, 🔧 버그 수정

#342 인기글, 해시태그 관련 리팩토링 및 수정
  backend/src/main/java/com/daily/daily/common/config/Business/BusinessConfig.java
  backend/src/main/java/com/daily/daily/post/dto/PostWriteRequestDTO.java
  backend/src/main/java/com/daily/daily/post/repository/PostRepositoryQuerydslImpl.java
  backend/src/main/java/com/daily/daily/post/service/HashtagService.java
  backend/src/main/java/com/daily/daily/post/service/PostLikeService.java
  backend/src/test/java/com/daily/daily/post/fixture/PostFixture.java
  backend/src/test/java/com/daily/daily/post/repository/PostRepositoryTest.java
  backend/src/test/java/com/daily/daily/post/service/HashtagServiceTest.java
  backend/src/test/java/com/daily/daily/post/service/PostServiceTest.java
Labels: BE

#337 다일리 커뮤니티 좋아요, 정렬관련 기능 추가
  frontend/src/apis/postApi.js
  frontend/src/components/common/Navigation/CommunityNavigation.jsx
  frontend/src/constants/posts.js
  frontend/src/pages/CommunityPage/CommunityPage.jsx
  frontend/src/pages/CommunityPage/CommunityPage.styled.jsx
  frontend/src/pages/CommunityPage/CommunityWritePage.jsx
  frontend/src/pages/DailryPage/DailryPage.jsx
  frontend/src/pages/MyPage/MyPage.jsx
  frontend/src/styles/color.js
  frontend/src/utils/toastify.js
Labels: FE, 🌱 신규 기능
